'use client';

import React, { useState, useEffect, useMemo } from 'react';
import { useRouter } from 'next/navigation';
import { FilePlus, Upload } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { Select } from '@/components/ui/select';
import { filterTeacherAssessments, resolveTeacherProfile } from '@/lib/teacherPortal';
import {
  countQuestionsInAssessmentMarkdown,
  isGeneratedAssessmentBlob,
} from '@/lib/assessmentMarkdown';
import type { Assessment } from '@/lib/mockData';
import {
  AisBtnPrimary,
  AisBtnSecondary,
  AisEmptyRow,
  AisPage,
  AisPanel,
  AisStatusBadge,
  AisTable,
  AisTd,
  AisTh,
  AisTr,
  approvalBadgeVariant,
  aisInput,
} from '@/components/dashboard/teacher/TeacherPortalUi';

export const TeacherAssessmentsTab: React.FC = () => {
  const router = useRouter();
  const { assessments, teachers, resolveTeacherId } = useApp();
  const teacherId = resolveTeacherId();
  const teacherProfile = resolveTeacherProfile(teachers, teacherId);
  const myAssessments = filterTeacherAssessments(assessments, teacherId, {
    subjects: teacherProfile.subjects,
  });
  const [searchQuery, setSearchQuery] = useState('');
  const [typeFilter, setTypeFilter] = useState<'All' | Assessment['type']>('All');
  const [statusFilter, setStatusFilter] = useState<'All' | Assessment['status']>('All');
  const filteredAssessments = useMemo(() => {
    return myAssessments.filter((a) => {
      if (typeFilter !== 'All' && a.type !== typeFilter) return false;
      if (statusFilter !== 'All' && a.status !== statusFilter) return false;
      const q = searchQuery.trim().toLowerCase();
      if (q && !a.title.toLowerCase().includes(q) && !a.subject.toLowerCase().includes(q)) return false;
      return true;
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [assessments, teacherId, typeFilter, statusFilter, searchQuery]);

  useEffect(() => {
    const open = () => router.push('/dashboard/teacher/assessments/generate');
    window.addEventListener('open-teacher-assessment', open);
    return () => window.removeEventListener('open-teacher-assessment', open);
  }, [router]);

  return (
    <AisPage>
      <AisPanel
        title="My assessments"
        description="Quizzes and baselines are ready immediately. Mid/final exams are generated by your HoD and appear once published."
        flush
        actions={
          <>
            <AisBtnPrimary onClick={() => router.push('/dashboard/teacher/assessments/generate')}>
              <FilePlus className="h-3.5 w-3.5" aria-hidden />
              Create quiz
            </AisBtnPrimary>
            <AisBtnSecondary onClick={() => router.push('/dashboard/teacher/assessments/generate?mode=upload')}>
              <Upload className="h-3.5 w-3.5" aria-hidden />
              Upload quiz file
            </AisBtnSecondary>
          </>
        }
      >
        <div className="grid grid-cols-1 gap-3 p-4 pb-0 sm:grid-cols-3">
          <input
            type="search"
            className={aisInput}
            placeholder="Search by title or subject..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <Select
            variant="ais"
            label=""
            options={[
              { value: 'All', label: 'All types' },
              { value: 'Quiz', label: 'Quiz' },
              { value: 'Mid Exam', label: 'Mid Exam' },
              { value: 'Final Exam', label: 'Final Exam' },
              { value: 'Assignment', label: 'Assignment' },
              { value: 'Practical', label: 'Practical' },
              { value: 'Baseline', label: 'Baseline' },
            ]}
            value={typeFilter}
            onChange={(e) => setTypeFilter(e.target.value as typeof typeFilter)}
          />
          <Select
            variant="ais"
            label=""
            options={[
              { value: 'All', label: 'All statuses' },
              { value: 'Draft', label: 'Draft' },
              { value: 'Pending Dept Head', label: 'Pending Dept Head' },
              { value: 'Approved', label: 'Approved' },
              { value: 'Rejected', label: 'Rejected' },
            ]}
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as typeof statusFilter)}
          />
        </div>
        <AisTable>
          <thead>
            <tr className="bg-ais-surface-container-low">
              <AisTh>Title</AisTh>
              <AisTh>Type</AisTh>
              <AisTh>Grade / Subject</AisTh>
              <AisTh>Difficulty</AisTh>
              <AisTh>Questions</AisTh>
              <AisTh>Status</AisTh>
            </tr>
          </thead>
          <tbody>
            {filteredAssessments.length === 0 ? (
              <AisEmptyRow colSpan={6} message="No assessments match this filter." />
            ) : (
              filteredAssessments.map((a) => (
                <AisTr
                  key={a.id}
                  className="cursor-pointer"
                  onClick={() => router.push(`/dashboard/teacher/assessments/${a.id}`)}
                >
                  <AisTd className="font-semibold text-primary hover:underline">
                    {a.title}
                    {a.createdByRole === 'department-head' ? (
                      <span className="ml-2 text-[10px] font-semibold uppercase tracking-wide text-ais-primary">
                        HoD
                      </span>
                    ) : null}
                  </AisTd>
                  <AisTd>{a.type}</AisTd>
                  <AisTd>{a.grade} · {a.subject}</AisTd>
                  <AisTd>{a.difficulty}</AisTd>
                  <AisTd className="tabular-nums">
                    {isGeneratedAssessmentBlob(a.questions)
                      ? countQuestionsInAssessmentMarkdown(a.questions[0].question)
                      : a.questions.length}
                  </AisTd>
                  <AisTd>
                    <AisStatusBadge variant={approvalBadgeVariant(a.status)}>{a.status}</AisStatusBadge>
                  </AisTd>
                </AisTr>
              ))
            )}
          </tbody>
        </AisTable>
      </AisPanel>
    </AisPage>
  );
};
